### PR TITLE
Features/narrow default strict

### PR DESCRIPTION
**Pull request by mikearnaldi**

### CODE REVIEW

**Comment by sledorze** [comment]
I need to ponder more on what it means to drop out `match` in favor of `matchWiden`.
I find it nice to have both variant (in some cases you want to take advantage of constraints).

**Comment by mikearnaldi** [comment]
Maybe remove default from match? In my opinion non narrowed default is really not good

**Comment by sledorze** [comment]
I have a working implementation for 'classical' matcher with narrowing

**Comment by mikearnaldi** [comment]
The weirdness doesn't end, apparently if you don't specify the parameter all breaks:

not-ok
ok

**Comment by sledorze** [comment]
handled by preview branch https://github.com/sledorze/morphic-ts/tree/preview/narrow-default-strict

**Pull request closed without merging**
