### PR TITLE
add iots config to interface and partial

### PR DESCRIPTION
**Pull request by mikearnaldi**

### CODE REVIEW

**Comment by mikearnaldi** [comment]
@sledorze based on your branch

**Comment by sledorze** [comment]
@mikearnaldi we've lost all inference on the type parameters in config (due to any usage and the removal of PropsE, PropsA).
We won't sacrifice type safety.

**Comment by mikearnaldi** [comment]
@sledorze I thought the type params were verbose looking at the primitive the params are never specified, if you want I can readd them

**Comment by mikearnaldi** [comment]
@sledorze added back params

**Comment by sledorze** [comment]
@mikearnaldi I've made the fixes

**Comment by mikearnaldi** [comment]
included in #24

**Pull request closed without merging**
